@url ="http://localhost:3000/"

//Book Flight
POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
    "title": "shipping",
    "price": 29000
}

###
//Get all Flights
Get http://localhost:3000/user HTTP/1.1


###
//Get a single flight
GET http://localhost:3000/user/876f857e-ab71-4744-aaa6-7e5cec6ce4da HTTP/1.1


//update flight
###
PUT http://localhost:3000/user/13912b55-d0de-4684-b4ae-78e7185aae6b HTTP/1.1
Content-Type: application/json

{
    "title": "service",
    "price": 35000
}
//Delete flight
###
DELETE http://localhost:3000/user/13912b55-d0de-4684-b4ae-78e7185aae6b HTTP/1.1