@url ="http://localhost:3000/"

//get all travellers
Get http://localhost:3000/user HTTP/1.1


###
//get a single user
GET http://localhost:3000/user/5735e4d0-f5fa-4708-9a74-d55fb06d516a HTTP/1.1

###
//add user
POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
    "title": "Conference",
    "time": "8:00am",
    "price": 20000,
    "date": "06-11-2022"
}